export default {
    SET_ERROR: 'SET_ERROR',
    SET_GENRES: 'SET_GENRES',
    SET_PLATFORMS: 'SET_PLATFORMS',
    SET_GAMES: 'SET_GAMES',
    SET_RESULT_DESIGN: 'SET_RESULT_DESIGN',
    SET_SELECTED_PAGE: 'SET_SELECTED_PAGE',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_SELECTED_GENRE: 'SET_SELECTED_GENRE',
    SET_SELECTED_PLATFORM: 'SET_SELECTED_PLATFORM',
    SET_CURRENT_GENRE: 'SET_CURRENT_GENRE',
    SET_CURRENT_PLATFORM: 'SET_CURRENT_PLATOFMR',
    SET_GAME_DETAILS: 'SET_GAME_DETAILS',
};